---
title: "tsa"
output: html_document
---

# --- Settings ---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# --- Packages ---

```{r}
library(tidyverse)
library(lubridate)
library(readxl)
```

# --- Data ---

# 1. Load

```{r}
raw <- readxl::read_xlsx("tsa.xlsx", sheet = 2)
```

# 2. View

```{r}
View(raw)
```

# Transform

```{r}
dat <-
raw %>% 
  mutate(date = mdy(date),
         travel = as.numeric(gsub(",", "", travel)))
```

```{r}
View(dat)
```


# --- Analysis ---

# 1. Graph

## 1.1. Simple

View flight info, over time, by year

```{r, fig.width=12, fig.height=5}
dat %>% 
  mutate(year = year(date),
         yday = yday(date),
         travel_m = travel/1e6,
         month = month(date, label = TRUE, abbr = TRUE)) %>% 
  ggplot(aes(x = yday,
             y = travel_m,
             color = as.factor(year))) +
  geom_point(size = 1) +
  geom_line(size = 1,
            alpha = 0.5) +
  theme_bw() +
  labs(title = "Airline Throughput Per Day",
       x = "Day",
       y = "Throughput (millions)",
       color = "Year") +
  scale_y_continuous(breaks = seq(0, 3, 0.5)) +
  #scale_x_date(date_breaks = month) +
  theme(plot.title = element_text(hjust = 0.5))
  
  
```

## 1.2. Right labels

Went here, to figure out x-axis/date labeling situation:

* https://community.rstudio.com/t/plot-weekly-data-with-monthly-axis-labels/62631


```{r, fig.width=12, fig.height=5}
plot_overlay <-
dat %>% 
  mutate(year = factor(year(date)),
         yday = yday(date),
         travel_m = travel/1e6) %>% 
  group_by(yday) %>% 
  mutate(date_grouped = last(date)) %>%
  filter(date != "2020-12-31") %>% # leap year shenanigans
  ggplot(aes(x = date_grouped,
             y = travel_m,
             color = as.factor(year))) +
  #geom_point() +
  geom_line(size = 0.75,
            alpha = 0.75) +
  theme_bw() +
  labs(title = "Daily Airline Travel",
       x = "",
       y = "Millions of People (crossing TSA checkpoint)",
       color = "Year") +
  scale_y_continuous(breaks = seq(0, 3, 0.5)) +
  scale_x_date(date_breaks = "1 month",
               date_labels = "%b") +
  theme(plot.title = element_text(hjust = 0.5),
        legend.position = "top")
plot_overlay
  
```


```{r, fig.width=12, fig.height=5}
plot_long <-
dat %>% 
  mutate(year = factor(year(date)),
         travel_m = travel/1e6) %>% 
  ggplot(aes(x = date,
             y = travel_m,
             color = as.factor(year))) +
  #geom_point() +
  geom_line(size = 0.75,
            alpha = 0.75) +
  theme_bw() +
  labs(title = "Daily Airline Travel",
       x = "",
       y = "Millions of People (crossing TSA checkpoint)",
       color = "Year") +
  scale_y_continuous(breaks = seq(0, 3, 0.5)) +
  scale_x_date(date_breaks = "2 month",
               date_labels = "%b \'%y") +
  theme(plot.title = element_text(hjust = 0.5),
        legend.position = "top")
plot_long

```


# 2. Save Plots

```{r}

ggsave(filename = "Airline Traffic (Overlay).pdf", plot = plot_overlay, width = 12, height = 5)
ggsave(filename = "Airline Traffic (Long).pdf", plot = plot_long, width = 12, height = 5)

```



# END/MISC


```{r}
dat %>% 
  mutate(year = factor(year(date)),
         yday = yday(date),
         travel_m = travel/1e6) %>% 
  group_by(yday) %>% 
  mutate(date_grouped = last(date)) %>%
  arrange(yday) 
```

```{r}
raw %>% 
  arrange(date)
```

```{r}
dat %>% 
  arrange(date)
```

